services:

  conduit-frontend:
    container_name: react-realworld
    image: conduit-frontend
    restart: always
    build: ./realworld-frontend
    ports:
      - "4100:4100"
    environment:
      - REACT_APP_BACKEND_URL=conduit-backend:3000
  
  conduit-backend:
    container_name: node-realworld
    image: conduit-backend
    build: ./realworld-backend
    ports: 
      - "3000:3000"
    environment:
      - NODE_OPTIONS="--max-old-space-size=4096"
      - TERM=xterm
    depends_on:
      - real_world

  real_world:
    container_name: database
    image: mysql:latest
    ports: 
      - "3306:3306"
    volumes:
      - ./backend/node-realworld/packages/server/sql/dump:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=realworld

volumes:
  realworld-volume: 